### GET request to example server
PUT http://localhost:4000/patients/abc@gmail.com
Content-Type: application/json

{
  "name": "John Doe",
  "email": "abc@gmail.com",
  "address": "123 main street",
  "dateOfBirth": "1987-10-17",
  "registeredDate": "2026-03-17"
}
###